#!/bin/bash -e

if [[ -z "$RUNIT_HUP_HACK" ]]; then
    exec "$@"
else
    # HACK runit sends HUP to PID 1, causing our shell to exit
    trap ':' HUP

    # Do not use exec here so our trap stays.
    "$@"
fi
